# datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vanhx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: vanhx123456
    type: com.zaxxer.hikari.HikariDataSource
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 3000
      pool-name: DatabookHikari
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: select 1
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  #使用 MD5 作为版本号
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  #redis
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8



#日志
debug: true
logging:
  level:
    com.van.common: debug






